inventory/models/inventory.py
from inventory.extensions import db
from datetime import datetime

class Inventory(db.Model):
  __tablename__ = 'inventory'
  inventory_id = db.Column(db.Integer, primary_key= True,nullable = False)
  location = db.Column(db.String(35),nullable = False)
  product_name = db.Column(db.String(35),nullable = False)
  product_qty = db.Column(db.Integer, nullable = False)
  
  def __repr__(self):
   return f"Inventory('{self.inventory_id}','{self.product_location}','{self.product_name}','{self.product_qty}')"
  

inventory/models/location.py
from inventory.extensions import db

class Location(db.Model):
  __tablename__ = 'location'
  location_id = db.Column(db.Integer, primary_key= True)
  location_name = db.Column(db.String(35),unique = True, nullable = False)
  def __repr__(self):
    return f"Location('{self.location_id}','{self.location_name}')"
    return "Location('{self.location_id}','{self.location_name}')"
  

inventory/models/product.py
from inventory.extensions import db

class Product(db.Model):
  __tablename__ = 'product'
  product_id = db.Column(db.Integer, primary_key= True)
  product_name = db.Column(db.String(35),unique = True ,nullable = False)
  product_qty = db.Column(db.Integer, nullable = False)
  def __repr__(self):
      return f"Product('{self.product_id}','{self.product_name}','{self.product_qty}')"
  

inventory/models/transfer.py
from inventory.extensions import db
from datetime import datetime

class Transfer(db.Model):
  __tablename__ = 'transfer'
  transfer_id = db.Column(db.Integer, primary_key= True)
  transfer_time = db.Column(db.DateTime, default=datetime.utcnow)
  transfer_to = db.Column(db.String(35),nullable = False)
  transfer_from = db.Column(db.String(35),nullable = False)
  product_name = db.Column(db.String(35),nullable = False)
  product_qty = db.Column(db.Integer, nullable = False)
  def __repr__(self):
   return f"Movement('{self.transfer_id}','{self.transfer_time}','{self.transfer_from}','{self.transfer_to}','{self.product_name}','{self.product_qty}')"
  

inventory/controllers/inventory.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, jsonify

from inventory.models.inventory import Inventory
from inventory.models.product import Product
from inventory.models.location import Location
from inventory.models.transfer import Transfer


from inventory.extensions import db

blueprint = Blueprint('inventory', __name__)


@blueprint.route('/inventory')
def index():
    data_inventory = Inventory.query.all()
    has_inventory = bool(data_inventory)
    # TODO: Pass has_inventory to render to display warning message

    return render_template('inventory/index.html',
                           data_inventory=data_inventory,
                           has_inventory=has_inventory)


@blueprint.route('/product', methods=['GET', 'POST'])
def product():
    if (request.method == "POST") and ('product_name'
                                       in request.form) and ('product_qty'
                                                             in request.form):
        product_name = request.form["product_name"]
        product_qty = request.form["product_qty"]
                                                              
        print({product_name, product_qty})
        new_product = Product(product_name=product_name,
                              product_qty=product_qty)

        try:
            db.session.add(new_product)
            db.session.commit()
            return redirect(url_for("product"))

        except:
            products = Product.query.order_by(Product.product_id).all()
            return render_template("inventory/product.html", products=products)
    else:
        products = Product.query.order_by(Product.product_id).all()
        print(products)
        return render_template("inventory/product.html", products=products)

@blueprint.route("/update-product/<product_id>", methods=["POST"])
def updateProduct(product_id):
    product = Product.query.get_or_404(product_id)
    old_product = product
  
    product.product_name   = request.form['product_name']
    product.product_qty   = request.form['product_qty']

    
    try:
        
        update_transfer=  Transfer.query\
        .join(Product, Transfer.product_name == old_product.product_name)\
        .add_columns(
            Transfer.transfer_id,
            Transfer.product_qty,
            Product.product_name, 
            Transfer.transfer_from,
            Transfer.transfer_to,
            Transfer.transfer_time)\
        .all()
        print(update_transfer)
        for trans in update_transfer:
          trans.product_name = product.product_name
          trans.product_qty = product.product_qty
        db.session.commit()
        return redirect("/product")

    except:
        print("There was an issue while updating the Product")
        render_template("inventory/product.html", error="There was an issue while updating the Product")


@blueprint.route("/location", methods=['GET', 'POST'])
def location():
  if (request.method == "POST") and ('location_name' in request.form):
    location_name = request.form["location_name"]
    new_location = Location(location_name=location_name)

    try:
      db.session.add(new_location)
      db.session.commit()
      return redirect("/location")

    except:
      locations = Location.query.order_by(Location.location_id).all()
      return render_template("inventory/location.html", locations=locations)
  else:
    locations = Location.query.order_by(Location.location_id).all()
    return render_template("inventory/location.html", locations=locations)
      

@blueprint.route("/update-location/<location_id>", methods=["POST"])
def updateLocation(location_id):
    location = Location.query.get_or_404(location_id)
    old_location = location
  
    location.location_name   = request.form['location_name']

    
    try:
        db.session.commit() 
        # trans1 = Transfer.query.filter(Transfer.transfer_from == old_location.transfer_from).all()
        # trans2 = Transfer.query.filter(Transfer.transfer_to == old_location.transfer_to).all()    

        # for tra in trans1:
        #   tra.transfer_to = location.transfer_to
        # for tra in trans2:
        #   tra.transfer_to = location.transfer_to
        # db.session.commit()
        return redirect("/location")

    except:
        print("There was an issue while updating the Product")
        render_template("inventory/location.html", error="There was an issue while updating the Product")


@blueprint.route("/transfers", methods=['GET', 'POST'])
def transfers():
  if request.method == "POST" :
    product_name      = request.form["product_name"]
    qty             = request.form["product_qty"]
    transfer_from    = request.form["transfer_from"]
    transfer_to      = request.form["transfer_to"]
    
    if transfer_from != transfer_to and transfer_to != transfer_from:
      new_transfer = Transfer(product_name=product_name, product_qty=qty, transfer_from=transfer_from, transfer_to=transfer_to)
      new_inventory = Inventory(location=transfer_to, product_name=product_name, product_qty=qty)
      
      try:
        db.session.add(new_transfer)
        db.session.add(new_inventory)
        db.session.commit()
        return redirect("/transfers")
      except:
        return render_template('inventory/transfer.html', error="There Was an issue while adding a new Transfer")
    else:
      products    = Product.query.order_by(Product.product_id).all()
      locations   = Location.query.order_by(Location.location_id).all()
      transfers = Transfer.query\
        .join(Product, Transfer.product_name == Product.product_name)\
        .add_columns(
            Transfer.transfer_id,
            Transfer.product_qty,
            Product.product_name, 
            Transfer.transfer_from,
            Transfer.transfer_to,
            Transfer.transfer_time)\
        .all()
      return render_template("inventory/transfer.html", transfers=transfers, products=products, locations=locations,  error="There Was an issue while adding a new Transfer")
  else:
    products    = Product.query.order_by(Product.product_id).all()
    locations   = Location.query.order_by(Location.location_id).all()
    transfers = Transfer.query\
        .join(Product, Transfer.product_name == Product.product_name)\
        .add_columns(
            Transfer.transfer_id,
            Transfer.product_qty,
            Product.product_name, 
            Transfer.transfer_from,
            Transfer.transfer_to,
            Transfer.transfer_time)\
        .all()
    
    return render_template("inventory/transfer.html", transfers=transfers, products=products, locations=locations)



@blueprint.route("/delete-product/<product_id>")
def deleteProduct(product_id):
    product_to_delete = Product.query.get_or_404(product_id)

    try:
        db.session.delete(product_to_delete)
        db.session.commit()
        return redirect("/product")
    except:
        return "There was an issue while deleteing the Product"
      
@blueprint.route("/delete-location/<location_id>")
def deleteLocation(location_id):
    location_to_delete = Location.query.get_or_404(location_id)

    try:
        db.session.delete(location_to_delete)
        db.session.commit()
        return redirect("/location")
    except:
        return "There was an issue while deleteing the Product"

inventory/templates/inventory/index.html
{% extends "layouts/layout.html" %}



{% block content %}
  <div class="container py-5 my-5" style="max-width: 980px;">
    
    <h1>Inventory Summary </h1>
    <div>
      <table class="table table-hover">
          <thead>
           <tr>
             <th>ID</th>
             <th></th>
             <th>Product</th>
             <th></th>
             <th>Warehouse</th>
             <th></th>
             <th>Quantity</th>
           </tr>
          </thead>
          <tbody>

          {%for data in data_inventory%}
           <tr>
             <td>{{data.inventory_id}}</td>
             <td></td>
             <td>{{data.product_name}}</td>
             <td></td>
             <td>{{data.location}}</td>
             <td></td>
             <td>{{data.quantity}}</td>
           </tr>

          {% endfor %}

          </table
            {% if not has_inventory %}
<div class="alert alert-warning" role="alert">
  You have no Product, Warhouse to display
</div>        {% endif %}
    </div>
  </div>
{% endblock %}

inventory/templates/inventory/location.html
{% extends "layouts/layout.html" %}


{% block content %}
<div class="container py-5 my-5" style="max-width: 980px;">
   <h1>Location</h1>
   <div class="mb-4" >
      <p style="display: inline-block;margin:0;"> Manage Product Location</p>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"> ➕ Add Location</button>
   </div>
   <div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLabel">Add Location</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            <form action="/location" method="POST" id="location_form">
               <div class="modal-body">
                 <div class="form-group mb-3">
                  <label for="location_name" class="col-form-label">Location Name</label>
                  <input type="text" name="location_name"  class="form-control" id="location_name">
                 </div>
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <input type="submit"id="submitLocation" value="Add Location" class="btn btn-primary">
               </div>
            </form>
         </div>
      </div>
   </div>
     
      <table class="table table-hover">
         <thead>
            <tr>
               <th>ID</th>
               <th>Name</th>
               <th></th>
               <th></th>
              <th  colspan="2">Actions</th>
            </tr>
         </thead>
         <tbody>
            {% for data in locations %}
            <tr>
               <td>{{data.location_id}}</td>
               <td>{{data.location_name}}</td>
              <td></td>
              <td></td>
               <td>
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target = "#editModal{{data.location_id}}" >
      Edit</button>
               </td>
               <td>
                  <a href="{{ url_for('inventory.deleteLocation', location_id = data.location_id) }}">
       <button type="button" class="btn btn-danger">
      Delete</button></a>
               </td>
            </tr>
           <div class="modal fade" id="editModal{{data.location_id}}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h5 class="modal-title" id="editModalLabel">Edit Location</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            <form action="{{ url_for('inventory.updateLocation', location_id = data.location_id) }}" method="POST" id="location_edit_form">
              <input type="hidden" name="locationid" value="{{data.location_id}}"/>
           
               <div class="modal-body">
                 <div class="form-group mb-3">
                  <label for="location_name" class="col-form-label">Location Name</label>
                  <input type="text" name="location_name"  class="form-control" id="location_name" value="{{data.location_name}}">
                 </div>
                
                   
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <input type="submit"id="submitLocation" value="Save Location" class="btn btn-primary">
               </div>
            </form>
         </div>
      </div>
   </div>
            {% endfor %}
         </tbody>
      </table>
   </div>
</div>
{% endblock %}

inventory/templates/inventory/product.html
{% extends "layouts/layout.html" %}
{% block content %}
<div class="container py-5 my-5" style="max-width: 980px;">
   <h1>Products</h1>
   <div class="mb-4" >
      <p style="display: inline-block;margin:0;"> Manage Products</p>
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal"> ➕ Add Product</button>
   </div>
   <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            <form action="/product" method="POST" id="product_form">
               <div class="modal-body">
                 <div class="form-group mb-3">
                  <label for="product_name" class="col-form-label">Product Name</label>
                  <input type="text" name="product_name"  class="form-control" id="product_name">
                 </div>
                  <div class="form-group mb-3">
                    
                   <label for="product_qty" class="col-form-label">Product QTY</label>
                  <input type="number" name="product_qty" class="form-control" id="product_qty">
                  </div>
                   
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <input type="submit"id="submitProduct" value="Add Product" class="btn btn-primary">
               </div>
            </form>
         </div>
      </div>
   </div>

      <table class="table table-hover">
         <thead>
            <tr>
               <th>ID</th>
               <th>Product</th>
               
               <th>Quantity</th>
              <th></th>
              <th></th>
              <th  colspan="2">Actions</th>
            </tr>
         </thead>
         <tbody>
            {%for data in products%}
            <tr>
               <td>{{data.product_id}}</td>
            
               <td>{{data.product_name}}</td>
          
               <td>{{data.product_qty}}</td>
              <td></td>
              <td></td>
              <td>
       <button type="button" class="btn btn-success" data-toggle="modal" data-target = "#editModal{{data.product_id}}" >
      Edit</button>

   </td>
              <td>
      <a href="{{ url_for('inventory.deleteProduct', product_id = data.product_id) }}">
       <button type="button" class="btn btn-danger">
      Delete</button></a>
   </td>
            </tr>

           <!--   Edit Modal -->
  <div class="modal fade" id="editModal{{data.product_id}}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h5 class="modal-title" id="editModalLabel">Edit Product</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            <form action="{{ url_for('inventory.updateProduct', product_id = data.product_id) }}" method="POST" id="product_edit_form">
              <input type="hidden" name="productid" value="{{data.prod_id}}"/>
           
               <div class="modal-body">
                 <div class="form-group mb-3">
                  <label for="product_name" class="col-form-label">Product Name</label>
                  <input type="text" name="product_name"  class="form-control" id="product_name" value="{{data.product_name}}">
                 </div>
                  <div class="form-group mb-3">
                    
                   <label for="product_qty" class="col-form-label">Product QTY</label>
                  <input type="number" name="product_qty" class="form-control" id="product_qty" value="{{data.product_qty}}">
                  </div>
                   
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <input type="submit"id="submitProduct" value="Save Product" class="btn btn-primary">
               </div>
            </form>
         </div>
      </div>
   </div>
   <div>
            {% endfor %}
      </table>
   </div>
</div>
{% endblock %}

inventory/templates/inventory/transfer.html
{% extends "layouts/layout.html" %}



{% block content %}
  <div class="container py-5 my-5" style="max-width: 980px;">
<h1>Transfers</h1>

<div class="mb-4" >
  <p style="display: inline-block;margin:0;"> Manage Product Transfers</p>
   <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal"> ➕ Move Product</button>

</div>  
     <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            <form action="/transfers" method="POST" id="product_form">
               <div class="modal-body">
                 <div class="form-group mb-3">
                  <label for="product_name" class="">Product Name</label>
                 <select class="form-select form-control" name="product_name" id="product_name" aria-label="Default select example">
  
               {% for product in products %}
          <option value="{{ product.product_name}}">{{product.product_name}}</option>
          {% endfor %}
</select>
                 </div>
                  <div class="form-group mb-3">
                    
                   <label for="transfer_from" class="">From Location</label>
                 <select class="form-select form-control" name="transfer_from" id="transfer_from" aria-label="Default select example">
  
               {% for location in locations %}
          <option value="{{ location.location_name}}">{{location.location_name}}</option>
          {% endfor %}
                 </select>
                  </div>
                   <div class="form-group mb-3">
                    
                   <label for="transfer_to" class="">To Location</label>
                  <select class="form-select form-control" name="transfer_to" id="transfer_to" aria-label="Default select example">
  
               {% for location in locations %}
          <option value="{{ location.location_name}}">{{location.location_name}}</option>
          {% endfor %}
                     </select>
                  </div>
                   
                  <div class="form-group mb-3">
                    
                   <label for="product_qty" class="">Product QTY</label>
                  <input type="number" name="product_qty" class="form-control" id="product_qty">
                  </div>
                   
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
               <input type="submit"id="submitTransfer" value="Submit Transfer" class="btn btn-primary">
               </div>
            </form>
         </div>
      </div>
   </div>
    
    <div>
<table class="table table-hover">
<thead>
 <tr>
   <th>ID</th>
   <th>Timestamp</th>
   <th>From</th>
   <th>To</th>
   <th>Product</th>
   <th>Quantity </th>
 </tr>
</thead>
<tbody>
{%for data in transfers%}
 <tr>
   <td>{{data.transfer_id}}</td>
   <td>{{data.transfer_time}}</td>
   <td>{{data.transfer_from}}</td>
   <td>{{data.transfer_to}}</td>
   <td>{{data.product_name}}</td>
   <td>{{data.product_qty}}</td>
 </tr>
 {% endfor %}
</tbody>
</table>
    </div>
  </div>
{% endblock %}